kind: pipeline
name: default

steps:
  - name: build
    image: docker:18.06-dind

    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

    commands:
      - dockerd --data-root /var/lib/docker
      - docker info
      - docker-compose build
      - docker login --username=$PLUGIN_USERNAME --password=$PLUGIN_PASSWORD
      - docker-compose push
